# Generated by Django 5.2 on 2025-05-01 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='category',
            new_name='categorie',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='colors',
            new_name='couleur',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='name',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='price',
            new_name='prix',
        ),
    ]
